educloud:
  config:
    ip-address: http://127.0.0.1
    eureka-port: 8761

#eureka配置
eureka:
  client:
    # Eureka服务器的地址
    service-url:
      defaultZone: ${educloud.config.ip-address}:${educloud.config.eureka-port}/eureka/
  instance:
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
    # 实例ID
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8300

spring:
  application:
    name: gatway

#zuul:
#  #自定义路由
#  routes:
#    system: /system/**


