server:
  port: 8002

spring:
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/educloud_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: admin
    password: admin

logging:
  level:
    com.xuegao.educloud.user.server.dao: ${educloud.sql-log-level}
